-- -------- < COLOCAR O NOME DE SEU PROJETO > --------
--
--                    SCRIPT DE CRIACAO (DDL)
--
-- Data Criacao ...........: 21/03/2018
-- Autor(es) ..............: Arthur da Silveira Sousa
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: booksA
--
-- PROJETO => 01 Base de Dados
--         => 11 Tabelas
--         => 03 Visoes
--         => 02 Perfis (role)
--         => 03 Usuarios
--         => 02 Sequencias
--         => 04 Triggers
--         => 02 Procedimentos
--         => 05 Funcoes

-- 
-- Ultimas Alteracoes
--   28/04/2018 => Alteracao na tabela PESSOA retirando idade.
--              => Incluido auto_increment na tabela PRODUTO.
--   29/04/2018 => Ajustes na apresentacao da documentacao
--                 desse script.
--
-- ---------------------------------------------------------

-- 1) Restauração do banco de dados 
-- 
-- mysql -u root -p booksA < backup_Projeto_booksA.sql
-- 
-- 2) 